### ISSUE TITLE
Push translated  README to PR branch instead of `main`

### ISSUE THREAD

**Issue by glenn-jocher** [dephraiim/translate-readme#13]
@dephraiim thanks for this action, it works really well! I'm trying to use it in https://github.com/ultralytics/yolov5.

I tried to update my yaml to create translations directly in Pull Requests in https://github.com/ultralytics/yolov5/pull/10445, but was unable to do so. Do you know if it's possible to do this? Use case would be for translated READMEs to form part of a larger PR, which is a little cleaner than being recorded as a separate commit to master.

The yaml I tried for this is here:
```yaml
name: Translate README

on:
  pull_request:
    branches:
      - main
      - master
    paths:
      - README.md
    
jobs:
  Translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      # ISO Langusge Codes: https://cloud.google.com/translate/docs/languages  
      - name: Adding README - Chinese Simplified
        uses: dephraiim/translate-readme@main
        with:
          LANG: zh-CN
```

And this is the error I get is 
```
(node:1711) UnhandledPromiseRejectionWarning: Error: Error: fatal: You are not currently on a branch.
```
<img width="976" alt="Screenshot 2022-12-08 at 16 41 17" src="https://user-images.githubusercontent.com/26833433/206596522-d88bc4a6-5e3c-4b0e-9e8b-d49c9ad0633f.png">

@ayushexel
