### ISSUE TITLE
Creating translations in given path

### ISSUE THREAD

**Issue by juanPabloMiceli** [dephraiim/translate-readme#6]
Is there any way of throwing the translations in a path described in the yml file? In my opinion having all these readmes in the root folder is a bit untidy.

**Comment by Minionguyjpro** [comment]
Try something like this:
```
      - name: Adding README  - German
        uses: dephraiim/translate-readme@main
        working-directory: ./img/
        with:
          LANG: de
```
This will set the working directory to a folder called "img". If you place an README.md in your directory, i think it translates that one.
